services:
  mex-editor:
    build: .
    image: mex-editor:local
    environment:
      MEX_EDITOR__BASE_HREF: "/editor/"

  httpd:
    image: httpd:2.4
    ports:
      - "8000:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - mex-editor
